language: nix
script: nix-build release.nix
deploy:
  provider: pages
  skip_cleanup: true
  on:
    branch: master
  local_dir: "./result/"
  github_token:
    secure: y7GuDWn7W5BzMdUx3d4t5YOvTKdHPeDpL9wNldS0e5F7Zb47rb7PnV7m2D0sY9Obb9bJVSGtDLJi1SXmuITuiqS+Qe2J4euhfHCTuev61oA8KCLZ0TGEDBp8w00INWLmP6MBlvbm21BVE6epH67X8oXgPJp3JtB/7Uc0soeX5JF+BVWC35nafaskblX5AzgGSfUcGPWcLGFRU96Jhe2YJqAdDmaGdaZIlD9GEFjYTtkjUq2mEAGRViFrGho2zj7JgtNATX0lstx81u4hdpT5STf28b2hnmmQB7u27GBghaEMVtBc4ONGFBSutctYOKiEmPfvXE66ezEM7dwJLotQlrdPydHnYLSK9Aqeb4M/eDw5ODfI0Z4aNYZ2U37Ufa/BMCuzU2Cej1eYXL170oG4OHTHMp+kB20e6m6+THddxEyVs5GHFYkVaueyHx8WoQuB9nFWfnFJR0s7GXz4M6sMA8tkZjfsidrfurivgWUkRsgD2XOgkEjI9D9YA69tX9sqSJU/f5FEjEBcVPqdxwjBXw0xJbAHATs6qLf7cCBoSmutOR6uV7Z9pd1DYP2jEzK/d/ivIT119RLKh0uFEu1Rv8fg0wWVD0kOCcC/J2c3UTG2Ao0RP/20CiHGcOa5+oKEKMjsqeIy9cio29ZKdp3GvzpZtOrGT3Icwi+KRgyWfkQ=
