language: generic
stages:
  - build
  - deploy

services:
  - docker

env:
  global:
    secure: Q0luGKQ5nDPHART1RiXiL7PkOiT3laAdRzzKX7mkNP0jRzcTHZwiW3A0tcq+G0yB9pmoI+XhXFt+Q2beVT0WmFSP6PrgH91p7nTO4NNbmk8x2w9bjEAgjJ+6WHBGScfCdTdZp8Tr/ZqAkoc9O5gEjQzkyZjCcUtKr7C37zAjXfARdxSjv7omH1jiQXY581jVFmNdrw+QMx/BxWBhLpUKSRJTtu28H8haejiXAVtI6h1sW/scY2blR702TEfYSudgYx8az70BJT+nMKoOdBWAwfg/wfu51WP6s9flIzidwp3CzfQUfDXB5a8EDyPgU+Anb4+pW3nNY/pj6PsZK7kyY2y7Xg76PjgrJnHxpjjX2P9bnQ9+DOh14LLv+XdeHR5rvjUYGG9PV1ZXRD86vB8LNTXgNYVfqRmuT4zZzM8O7iIq7njxnc0iJiyyJZbAMZ9JnF278uWWbXKJmcKaZhYmd3fc3mSM5GzUgBSDS5nw2YsX002VFzPy1ljOmmcG/3zPqy3TxHpPFtMlCZ1zIkyoyPkDFEk17XM0iaxT2VtXvhj/vAvkfKP/Pbi7HOR3mOx7/j5/HCnZ6kk5h6L4ykBBC0Ciho8WGQJIL9wo0UtQuAi+PizwNmqpg+Wz0w+4co+dFguW7v/i8AlAWC7B1kS87vXWibi1qsaH+C3VlF9t0zw=

jobs:
  include:
    - language: nix
      stage: build
      script:
        - nix-env -iA cachix -f https://cachix.org/api/v1/install
        - cachix use thalesmg
        - if [ -n "$CACHIX_SIGNING_KEY" ]; then cachix push thalesmg --watch-store; fi &
        - nix-build release.nix
        - mkdir -p ./dist
        - mkdir -p ./fns
        - cp -r ./result/* ./dist
        - rm ./result
        - zip -r dist.zip ./dist/
        - docker run --rm -e TRAVIS_BUILD_ID -e IBMC_API_KEY -v $PWD:/mnt thalesmg/ibmccos:v1.0 /mnt/obj.sh put dist.zip

    - language: rust
      stage: build
      rust: stable
      addons:
        apt:
          packages:
            # For building MUSL static builds on Linux.
            - musl-tools
      script:
        - rustup target add x86_64-unknown-linux-musl
        - cd netlify
        - cargo build --target x86_64-unknown-linux-musl --release
        - cd -
        - mkdir -p ./fns/
        - cp netlify/target/x86_64-unknown-linux-musl/release/rust-static-nix ./fns/xablau
        - zip -r fns.zip ./fns/
        - docker run --rm -e TRAVIS_BUILD_ID -e IBMC_API_KEY -v $PWD:/mnt thalesmg/ibmccos:v1.0 /mnt/obj.sh put fns.zip
      cache: cargo

    # - stage: deploy
    #   before_deploy:
    #     script:
    #       - docker run --rm -e TRAVIS_BUILD_ID -e IBMC_API_KEY -v $PWD:/mnt thalesmg/ibmccos:v1.0 /mnt/obj.sh get fns.zip
    #       - docker run --rm -e TRAVIS_BUILD_ID -e IBMC_API_KEY -v $PWD:/mnt thalesmg/ibmccos:v1.0 /mnt/obj.sh get dist.zip
    #       - unzip dist.zip
    #       - unzip fns.zip
    #   deploy:
    #     - provider: pages:git
    #       edge: true
    #       skip_cleanup: true
    #       on:
    #         branch: master
    #       local_dir: ./dist/
    #       token:
    #         secure: IsttZaz7j8pAvBGsuGxytnHuQ6D8CXV9vXhZ0UO12MwieEAnpJqWeU3Spk6oQ+cJXkxktA8REtW8j9l29W74pvd2LJkyeF4brb8pRO0XghY+kkxnc8BtacjRQ6eqtZlpxOGrSYN/5eOFb7e1vQqzNjb7c91Snlo08nEc3+5srxbIKc4+9gHN0IhB8DU2Iy2VvW7tt/7TLkec4DOHWnmh1TK/+dRYG6g9+DwNOiRnqLaj3nl/awU3Od5lM0yi+htZht/9wwnbELDkHt6yBu7/DE5rtW2VZo+qjoebWNgrJwjtuymN41xTztkwR5KNUgVvQGm1zSpMkhkDzwIAg7YDakHoSSBBflLPxs3KTN3ALilvNmaUJnLl/+BsbTFbyu3YpxExOY9p0TNVmXR+73Yo/eG3ilCFxxguH+7cMjHXhBvJ99FFKcm3M2aWUgJ8ndQ/7Effo3SSHKth/vE6Q5BfLCqrSQnI9pjlCkPCu+fAAGJ9yV/VOQGuUp/VYD7neSWgc7trMKFmBEIR4RcZl/Guz+wgkqECCCLCeSxQCcISm2UB1MTdDSxwMX5Js5mKLG2sj+7FBG9gSnsbLteDFYc0ZDYBq+V1VX3W3Pkjp2dVMTwsO4WXTfpANOOOuFXwjf95avz5AYFiLeZggsm9KPC6LDl2RHM8cRfs/uRtCirWjFw=

    #     - provider: netlify
    #       edge: yes
    #       skip_cleanup: yes
    #       on:
    #         all_branches: yes
    #       auth:
    #         secure: "0vJMjQ1G7kq+DjSdfWBYGDTqp4lsAUDUP5wA9xMMGmH0l7PsFgnkdmxwgY14X60oqhjTw/lC2EZEPlk3Mc38pqL8VOrYqvc8W9IDF6cJphJtI3NEFnqW3CnJcMskhBvqqSuUllNuq9jXtie/9FElpSxKS2yTTLF/KrwPI6wtHJbLEDSzi7v9WLkDpJh5qDcsplzqUcTP9KZy/NeWw1SAKjsLFc5JvIV7Q9NoBKbIDbUHVo8Nd58ghPTRp6jji35iUJPHJGYkfIK2crXNwWJIS6i+xrQ4qqHJ2hnE3BnIoSeVlQOvTMCBIaUHjnZKSWfVqF0x9ZKJTrMCBZrv82lxXlkV9Z6K2IjUZRI55D2au3xrIBMCJh9ehwMoNrRdibuXvMJWYiM0GlW0Um/fX+qT4eAnM3fq3lgVufS+OhlwFIsF2YFFS7a6x2TjTicfakNf0DbkQE4NMtH3yhKF7lYl7bhcp9OeBbQauTrXj/q99OKXir5nS2LENZ+n4/DrQQkabpXp7TFOpjbgL/m2joKcR2J+iSFGfP15MP9liRcZKVCemQ6Z5EAQS++9991kazFl3Hl4iNaJGRumsAqa8uUOQ/mcJmDZcFZN6WY0UYio1a5jyYOf+P9gWumdrmNsPoRRm+rESYfw1Cf6IO9a2EUXePbdQhYpy6gW9MZTukW6jDA="
    #       site: a1558d73-d6e5-4050-92cd-12a8828235af
    #       prod: no
    #       dir: ./dist/
    #       functions: ./fns/

    #     - provider: netlify
    #       edge: yes
    #       skip_cleanup: yes
    #       on:
    #         branch: master
    #       auth:
    #         secure: "0vJMjQ1G7kq+DjSdfWBYGDTqp4lsAUDUP5wA9xMMGmH0l7PsFgnkdmxwgY14X60oqhjTw/lC2EZEPlk3Mc38pqL8VOrYqvc8W9IDF6cJphJtI3NEFnqW3CnJcMskhBvqqSuUllNuq9jXtie/9FElpSxKS2yTTLF/KrwPI6wtHJbLEDSzi7v9WLkDpJh5qDcsplzqUcTP9KZy/NeWw1SAKjsLFc5JvIV7Q9NoBKbIDbUHVo8Nd58ghPTRp6jji35iUJPHJGYkfIK2crXNwWJIS6i+xrQ4qqHJ2hnE3BnIoSeVlQOvTMCBIaUHjnZKSWfVqF0x9ZKJTrMCBZrv82lxXlkV9Z6K2IjUZRI55D2au3xrIBMCJh9ehwMoNrRdibuXvMJWYiM0GlW0Um/fX+qT4eAnM3fq3lgVufS+OhlwFIsF2YFFS7a6x2TjTicfakNf0DbkQE4NMtH3yhKF7lYl7bhcp9OeBbQauTrXj/q99OKXir5nS2LENZ+n4/DrQQkabpXp7TFOpjbgL/m2joKcR2J+iSFGfP15MP9liRcZKVCemQ6Z5EAQS++9991kazFl3Hl4iNaJGRumsAqa8uUOQ/mcJmDZcFZN6WY0UYio1a5jyYOf+P9gWumdrmNsPoRRm+rESYfw1Cf6IO9a2EUXePbdQhYpy6gW9MZTukW6jDA="
    #       site: a1558d73-d6e5-4050-92cd-12a8828235af
    #       prod: yes
    #       dir: ./dist/


# script:
#   - nix-env -iA cachix -f https://cachix.org/api/v1/install
#   - cachix use thalesmg
#   - if [ -n "$CACHIX_SIGNING_KEY" ]; then cachix push thalesmg --watch-store; fi &
#   # - ./heartbeat.sh &
#   # - nix-build functions.nix -o functions 2>/dev/null
#   - cd netlify
#   - nix-shell --run "cargo build --target x86_64-unknown-linux-musl --release"
#   - cd -
#   - nix-build release.nix
#   - mkdir -p ./dist
#   - mkdir -p ./fns
#   - cp netlify/target/x86_64-unknown-linux-musl/release/rust-static-nix ./fns/xablau
#   - cp -r ./result/* ./dist
#   # - cp ./functions/bin/* ./fns/
#   - cp ./netlify/fns/teste.js ./fns/
#   - rm ./result
#   # - rm ./functions
#   - sleep 10

before_deploy:
  - docker run --rm -e TRAVIS_BUILD_ID -e IBMC_API_KEY -v $PWD:/mnt thalesmg/ibmccos:v1.0 /mnt/obj.sh get fns.zip
  - docker run --rm -e TRAVIS_BUILD_ID -e IBMC_API_KEY -v $PWD:/mnt thalesmg/ibmccos:v1.0 /mnt/obj.sh get dist.zip
  - unzip dist.zip
  - unzip fns.zip

deploy:
  - provider: pages:git
    stage: deploy
    edge: true
    skip_cleanup: true
    on:
      branch: master
    local_dir: ./dist/
    token:
      secure: IsttZaz7j8pAvBGsuGxytnHuQ6D8CXV9vXhZ0UO12MwieEAnpJqWeU3Spk6oQ+cJXkxktA8REtW8j9l29W74pvd2LJkyeF4brb8pRO0XghY+kkxnc8BtacjRQ6eqtZlpxOGrSYN/5eOFb7e1vQqzNjb7c91Snlo08nEc3+5srxbIKc4+9gHN0IhB8DU2Iy2VvW7tt/7TLkec4DOHWnmh1TK/+dRYG6g9+DwNOiRnqLaj3nl/awU3Od5lM0yi+htZht/9wwnbELDkHt6yBu7/DE5rtW2VZo+qjoebWNgrJwjtuymN41xTztkwR5KNUgVvQGm1zSpMkhkDzwIAg7YDakHoSSBBflLPxs3KTN3ALilvNmaUJnLl/+BsbTFbyu3YpxExOY9p0TNVmXR+73Yo/eG3ilCFxxguH+7cMjHXhBvJ99FFKcm3M2aWUgJ8ndQ/7Effo3SSHKth/vE6Q5BfLCqrSQnI9pjlCkPCu+fAAGJ9yV/VOQGuUp/VYD7neSWgc7trMKFmBEIR4RcZl/Guz+wgkqECCCLCeSxQCcISm2UB1MTdDSxwMX5Js5mKLG2sj+7FBG9gSnsbLteDFYc0ZDYBq+V1VX3W3Pkjp2dVMTwsO4WXTfpANOOOuFXwjf95avz5AYFiLeZggsm9KPC6LDl2RHM8cRfs/uRtCirWjFw=

  - provider: netlify
    stage: deploy
    edge: yes
    skip_cleanup: yes
    on:
      all_branches: yes
    auth:
      secure: "0vJMjQ1G7kq+DjSdfWBYGDTqp4lsAUDUP5wA9xMMGmH0l7PsFgnkdmxwgY14X60oqhjTw/lC2EZEPlk3Mc38pqL8VOrYqvc8W9IDF6cJphJtI3NEFnqW3CnJcMskhBvqqSuUllNuq9jXtie/9FElpSxKS2yTTLF/KrwPI6wtHJbLEDSzi7v9WLkDpJh5qDcsplzqUcTP9KZy/NeWw1SAKjsLFc5JvIV7Q9NoBKbIDbUHVo8Nd58ghPTRp6jji35iUJPHJGYkfIK2crXNwWJIS6i+xrQ4qqHJ2hnE3BnIoSeVlQOvTMCBIaUHjnZKSWfVqF0x9ZKJTrMCBZrv82lxXlkV9Z6K2IjUZRI55D2au3xrIBMCJh9ehwMoNrRdibuXvMJWYiM0GlW0Um/fX+qT4eAnM3fq3lgVufS+OhlwFIsF2YFFS7a6x2TjTicfakNf0DbkQE4NMtH3yhKF7lYl7bhcp9OeBbQauTrXj/q99OKXir5nS2LENZ+n4/DrQQkabpXp7TFOpjbgL/m2joKcR2J+iSFGfP15MP9liRcZKVCemQ6Z5EAQS++9991kazFl3Hl4iNaJGRumsAqa8uUOQ/mcJmDZcFZN6WY0UYio1a5jyYOf+P9gWumdrmNsPoRRm+rESYfw1Cf6IO9a2EUXePbdQhYpy6gW9MZTukW6jDA="
    site: a1558d73-d6e5-4050-92cd-12a8828235af
    prod: no
    dir: ./dist/
    functions: ./fns/

  - provider: netlify
    stage: deploy
    edge: yes
    skip_cleanup: yes
    on:
      branch: master
    auth:
      secure: "0vJMjQ1G7kq+DjSdfWBYGDTqp4lsAUDUP5wA9xMMGmH0l7PsFgnkdmxwgY14X60oqhjTw/lC2EZEPlk3Mc38pqL8VOrYqvc8W9IDF6cJphJtI3NEFnqW3CnJcMskhBvqqSuUllNuq9jXtie/9FElpSxKS2yTTLF/KrwPI6wtHJbLEDSzi7v9WLkDpJh5qDcsplzqUcTP9KZy/NeWw1SAKjsLFc5JvIV7Q9NoBKbIDbUHVo8Nd58ghPTRp6jji35iUJPHJGYkfIK2crXNwWJIS6i+xrQ4qqHJ2hnE3BnIoSeVlQOvTMCBIaUHjnZKSWfVqF0x9ZKJTrMCBZrv82lxXlkV9Z6K2IjUZRI55D2au3xrIBMCJh9ehwMoNrRdibuXvMJWYiM0GlW0Um/fX+qT4eAnM3fq3lgVufS+OhlwFIsF2YFFS7a6x2TjTicfakNf0DbkQE4NMtH3yhKF7lYl7bhcp9OeBbQauTrXj/q99OKXir5nS2LENZ+n4/DrQQkabpXp7TFOpjbgL/m2joKcR2J+iSFGfP15MP9liRcZKVCemQ6Z5EAQS++9991kazFl3Hl4iNaJGRumsAqa8uUOQ/mcJmDZcFZN6WY0UYio1a5jyYOf+P9gWumdrmNsPoRRm+rESYfw1Cf6IO9a2EUXePbdQhYpy6gW9MZTukW6jDA="
    site: a1558d73-d6e5-4050-92cd-12a8828235af
    prod: yes
    dir: ./dist/
