language: nix
script:
  - nix-build release.nix
  - mkdir -p ./dist
  - cp -r ./result/* ./dist
  - rm ./result

deploy:
  - provider: pages:git
    edge: true
    skip_cleanup: true
    on:
      branch: master
    local_dir: ./dist/
    token:
      secure: IsttZaz7j8pAvBGsuGxytnHuQ6D8CXV9vXhZ0UO12MwieEAnpJqWeU3Spk6oQ+cJXkxktA8REtW8j9l29W74pvd2LJkyeF4brb8pRO0XghY+kkxnc8BtacjRQ6eqtZlpxOGrSYN/5eOFb7e1vQqzNjb7c91Snlo08nEc3+5srxbIKc4+9gHN0IhB8DU2Iy2VvW7tt/7TLkec4DOHWnmh1TK/+dRYG6g9+DwNOiRnqLaj3nl/awU3Od5lM0yi+htZht/9wwnbELDkHt6yBu7/DE5rtW2VZo+qjoebWNgrJwjtuymN41xTztkwR5KNUgVvQGm1zSpMkhkDzwIAg7YDakHoSSBBflLPxs3KTN3ALilvNmaUJnLl/+BsbTFbyu3YpxExOY9p0TNVmXR+73Yo/eG3ilCFxxguH+7cMjHXhBvJ99FFKcm3M2aWUgJ8ndQ/7Effo3SSHKth/vE6Q5BfLCqrSQnI9pjlCkPCu+fAAGJ9yV/VOQGuUp/VYD7neSWgc7trMKFmBEIR4RcZl/Guz+wgkqECCCLCeSxQCcISm2UB1MTdDSxwMX5Js5mKLG2sj+7FBG9gSnsbLteDFYc0ZDYBq+V1VX3W3Pkjp2dVMTwsO4WXTfpANOOOuFXwjf95avz5AYFiLeZggsm9KPC6LDl2RHM8cRfs/uRtCirWjFw=

  - provider: netlify
    edge: yes
    skip_cleanup: yes
    on:
      all_branches: yes
    auth:
      secure: "0vJMjQ1G7kq+DjSdfWBYGDTqp4lsAUDUP5wA9xMMGmH0l7PsFgnkdmxwgY14X60oqhjTw/lC2EZEPlk3Mc38pqL8VOrYqvc8W9IDF6cJphJtI3NEFnqW3CnJcMskhBvqqSuUllNuq9jXtie/9FElpSxKS2yTTLF/KrwPI6wtHJbLEDSzi7v9WLkDpJh5qDcsplzqUcTP9KZy/NeWw1SAKjsLFc5JvIV7Q9NoBKbIDbUHVo8Nd58ghPTRp6jji35iUJPHJGYkfIK2crXNwWJIS6i+xrQ4qqHJ2hnE3BnIoSeVlQOvTMCBIaUHjnZKSWfVqF0x9ZKJTrMCBZrv82lxXlkV9Z6K2IjUZRI55D2au3xrIBMCJh9ehwMoNrRdibuXvMJWYiM0GlW0Um/fX+qT4eAnM3fq3lgVufS+OhlwFIsF2YFFS7a6x2TjTicfakNf0DbkQE4NMtH3yhKF7lYl7bhcp9OeBbQauTrXj/q99OKXir5nS2LENZ+n4/DrQQkabpXp7TFOpjbgL/m2joKcR2J+iSFGfP15MP9liRcZKVCemQ6Z5EAQS++9991kazFl3Hl4iNaJGRumsAqa8uUOQ/mcJmDZcFZN6WY0UYio1a5jyYOf+P9gWumdrmNsPoRRm+rESYfw1Cf6IO9a2EUXePbdQhYpy6gW9MZTukW6jDA="
    site: a1558d73-d6e5-4050-92cd-12a8828235af
    prod: no
    dir: ./dist/

  - provider: netlify
    edge: yes
    skip_cleanup: yes
    on:
      branch: master
    auth:
      secure: "0vJMjQ1G7kq+DjSdfWBYGDTqp4lsAUDUP5wA9xMMGmH0l7PsFgnkdmxwgY14X60oqhjTw/lC2EZEPlk3Mc38pqL8VOrYqvc8W9IDF6cJphJtI3NEFnqW3CnJcMskhBvqqSuUllNuq9jXtie/9FElpSxKS2yTTLF/KrwPI6wtHJbLEDSzi7v9WLkDpJh5qDcsplzqUcTP9KZy/NeWw1SAKjsLFc5JvIV7Q9NoBKbIDbUHVo8Nd58ghPTRp6jji35iUJPHJGYkfIK2crXNwWJIS6i+xrQ4qqHJ2hnE3BnIoSeVlQOvTMCBIaUHjnZKSWfVqF0x9ZKJTrMCBZrv82lxXlkV9Z6K2IjUZRI55D2au3xrIBMCJh9ehwMoNrRdibuXvMJWYiM0GlW0Um/fX+qT4eAnM3fq3lgVufS+OhlwFIsF2YFFS7a6x2TjTicfakNf0DbkQE4NMtH3yhKF7lYl7bhcp9OeBbQauTrXj/q99OKXir5nS2LENZ+n4/DrQQkabpXp7TFOpjbgL/m2joKcR2J+iSFGfP15MP9liRcZKVCemQ6Z5EAQS++9991kazFl3Hl4iNaJGRumsAqa8uUOQ/mcJmDZcFZN6WY0UYio1a5jyYOf+P9gWumdrmNsPoRRm+rESYfw1Cf6IO9a2EUXePbdQhYpy6gW9MZTukW6jDA="
    site: a1558d73-d6e5-4050-92cd-12a8828235af
    prod: yes
    dir: ./dist/

after_deploy:
  - python3 --version
